# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [55]:
print(" list() 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；\n tolist() 才能達成多層的型態轉換。") 

 list() 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；
 tolist() 才能達成多層的型態轉換。


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [35]:
# 記得先 Import 正確的套件

import numpy as np

In [36]:

a = np.random.randint(10, size=6) 

print(a)    # 印出 NdArray 的內容值
print("維度:", a.ndim)   # 印出 NdArray 有多少維度
print("維度的大小:", a.shape)   # 印出 NdArray 每個維度的大小
print("有幾個元素:", a.size)   # 印出 NdArray 中有幾個元素
print("資料型態:", a.dtype)  # 印出 NdArray 的資料型態
print("每個元素佔用的空間:", a.itemsize)   # 印出 NdArray 每個元素佔用的空間
print("長度:", len(a))   # 印出 NdArray 的長度
print("類型:", type(a))  # 印出 NdArray 的類型

[6 9 6 0 5 5]
維度: 1
維度的大小: (6,)
有幾個元素: 6
資料型態: int32
每個元素佔用的空間: 4
長度: 6
類型: <class 'numpy.ndarray'>


In [37]:
b = np.random.randint(10, size=(3,4)) 

print(b)    # 印出 NdArray 的內容值
print("維度:", b.ndim)   # 印出 NdArray 有多少維度
print("維度的大小:", b.shape)   # 印出 NdArray 每個維度的大小
print("有幾個元素:", b.size)   # 印出 NdArray 中有幾個元素
print("資料型態:", b.dtype)  # 印出 NdArray 的資料型態
print("每個元素佔用的空間:", b.itemsize)   # 印出 NdArray 每個元素佔用的空間
print("長度:", len(b))   # 印出 NdArray 的長度
print("類型:", type(b))  # 印出 NdArray 的類型

[[9 3 4 6]
 [3 6 5 5]
 [8 5 9 3]]
維度: 2
維度的大小: (3, 4)
有幾個元素: 12
資料型態: int32
每個元素佔用的空間: 4
長度: 3
類型: <class 'numpy.ndarray'>


In [38]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)    # 印出 NdArray 的內容值
print("維度:", c.ndim)   # 印出 NdArray 有多少維度
print("維度的大小:", c.shape)   # 印出 NdArray 每個維度的大小
print("有幾個元素:", c.size)   # 印出 NdArray 中有幾個元素
print("資料型態:", c.dtype)  # 印出 NdArray 的資料型態
print("每個元素佔用的空間:", c.itemsize)   # 印出 NdArray 每個元素佔用的空間
print("長度:", len(c))   # 印出 NdArray 的長度
print("類型:", type(c))  # 印出 NdArray 的類型

[[[0 3]
  [5 0]
  [0 4]]

 [[2 9]
  [0 7]
  [0 5]]]
維度: 3
維度的大小: (2, 3, 2)
有幾個元素: 12
資料型態: int32
每個元素佔用的空間: 4
長度: 2
類型: <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [49]:
def tolist(data):
    if type(data) != np.ndarray:
        return data
    newlist = []
    for item in data:
        newlist.append(tolist(item))
    return tolist(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 9, 6, 0, 5, 5]
[[9, 3, 4, 6], [3, 6, 5, 5], [8, 5, 9, 3]]
[[[0, 3], [5, 0], [0, 4]], [[2, 9], [0, 7], [0, 5]]]


In [52]:
def tolist(data):
    if type(data) != np.ndarray:
        return data
    return [tolist(item) for item in data]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 9, 6, 0, 5, 5]
[[9, 3, 4, 6], [3, 6, 5, 5], [8, 5, 9, 3]]
[[[0, 3], [5, 0], [0, 4]], [[2, 9], [0, 7], [0, 5]]]
